[package]
name = "trace"
version = "0.1.1"
authors = ["Gulshan Singh <gsingh2011@gmail.com>"]
repository = "https://github.com/gsingh93/trace"
license = "MIT"
description = "A syntax extension for tracing the execution of functions"

[lib]
name = "trace"
plugin = true
